### ISSUE TITLE
Scope of generated code

### ISSUE THREAD

**Issue by Scooletz** [NethermindEth/IL-EVM#2]
The following options are laid out in regards to what can be pre-generated:

1. full contract, for example `Uniswap`
2. partial, for example a sequence of opcodes that does some math without state that can be replaced

The decision should be provided which of these do we target.

**Comment by Demuirgos** [comment]
* the first approach seems promising for now with the current iteration of the EVM (since code sections and function as native constructs dont exist it's super hard to gather metadata data about what's a hot path [maybe branches can be used as an alternative but I think it's not as straight forward]).
* the second approach is ideal imo if EOF makes it to the EVM (which is either months from now or perhaps years)

**Comment by Demuirgos** [comment]
or come to think of it we can analyze smart contracts to extract if there are long "pure" sequences of code that can be swapped with IL their IL counterpart or JITed

**Comment by Scooletz** [comment]
I think I'd go with a `partial` as it can be progressively extended into more complex scenarios. We could start with something as "no jumps, memory or storage" as a requirement and later build more and more. Effectively, partial could evolve into `full contract` later on. The next advantage of `partial` is making the #5 much easier. We can generate to do not step over the interaction with another one.

**Comment by Scooletz** [comment]
**Partial**

We're going initially with partial so that it's extended later on.
